application: akli-reguig
version: 1
runtime: go
api_version: go1



handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /cv
  static_files: static/cv.html
  upload: static/cv.html

- url: /ts
  static_files: static/t_selector.html
  upload: static/t_selector.html

- url: /(.*\.(css|gif|png|jpg|ico|js|html))
  static_files: static/\1
  upload: static/(.*\.(css|gif|png|jpg|ico|js|html))

- url: /.*
  script: _go_app
